CREATE TABLE IF NOT EXISTS "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL,
  "login" varchar,
  "username" varchar,
  "birthday" date
);

CREATE TABLE IF NOT EXISTS "friends" (
  "user_id" bigint NOT NULL,
  "friend_id" bigint NOT NULL,
  "friendship_status_id" int,
  PRIMARY KEY ("user_id", "friend_id")
);

CREATE TABLE IF NOT EXISTS "friendship_status" (
  "friendship_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar
);

CREATE TABLE IF NOT EXISTS "films" (
  "film_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "release_date" date,
  "duration" int,
  "rating_id" int
);

CREATE TABLE IF NOT EXISTS "rating" (
  "rating_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rating" varchar
);

CREATE TABLE IF NOT EXISTS "likes" (
  "film_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("film_id", "user_id")
);

CREATE TABLE IF NOT EXISTS "films_gerne" (
  "film_id" bigint NOT NULL,
  "gerne_id" int NOT NULL,
  PRIMARY KEY ("film_id", "gerne_id")
);

CREATE TABLE IF NOT EXISTS "gerne" (
  "gerne_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gerne" varchar
);

ALTER TABLE "friends" ADD FOREIGN KEY ("friendship_status_id") REFERENCES "friendship_status" ("friendship_status_id");

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "friends" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("user_id");

ALTER TABLE "films" ADD FOREIGN KEY ("rating_id") REFERENCES "rating" ("rating_id");

ALTER TABLE "likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "films_gerne" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "films_gerne" ADD FOREIGN KEY ("gerne_id") REFERENCES "gerne" ("gerne_id");