CREATE TABLE IF NOT EXISTS "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL,
  "login" varchar,
  "username" varchar,
  "birthday" date
);

CREATE TABLE IF NOT EXISTS "friends" (
  "user_id" bigint NOT NULL,
  "friend_id" bigint NOT NULL,
  "friendship_status_id" int,
  PRIMARY KEY ("user_id", "friend_id")
);

CREATE TABLE IF NOT EXISTS "friendship_status" (
  "friendship_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar
);

CREATE TABLE IF NOT EXISTS "films" (
  "film_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "release_date" date,
  "duration" int,
  "mpa_id" int
);

CREATE TABLE IF NOT EXISTS "mpas" (
  "mpa_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mpa" varchar
);

CREATE TABLE IF NOT EXISTS "likes" (
  "film_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("film_id", "user_id")
);

CREATE TABLE IF NOT EXISTS "films_genre" (
  "film_id" bigint NOT NULL,
  "genre_id" int NOT NULL,
  PRIMARY KEY ("film_id", "genre_id")
);

CREATE TABLE IF NOT EXISTS "genres" (
  "genre_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "genre" varchar
);

CREATE TABLE IF NOT EXISTS "user_events" (
  "user_event_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" bigint,
  "user_id" bigint,
  "entity_id" bigint,
  "event_type_id" int,
  "operation_type_id" int
);

CREATE TABLE IF NOT EXISTS "event_types" (
  "event_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE IF NOT EXISTS "operation_types" (
  "operation_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

ALTER TABLE "friends" ADD FOREIGN KEY ("friendship_status_id") REFERENCES "friendship_status" ("friendship_status_id");

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "friends" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("user_id");

ALTER TABLE "films" ADD FOREIGN KEY ("mpa_id") REFERENCES "mpas" ("mpa_id");

ALTER TABLE "likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "films_genre" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "films_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("genre_id");

ALTER TABLE "user_events" ADD FOREIGN KEY ("event_type_id") REFERENCES "event_types" ("event_type_id");

ALTER TABLE "user_events" ADD FOREIGN KEY ("operation_type_id") REFERENCES "operation_types" ("operation_type_id");